# Generated by Django 5.0.6 on 2024-06-12 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь(я)', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
